### ISSUE TITLE
Refactor PharmacistMenu

### ISSUE THREAD

**Issue by lowkanyui** [nonnoxer/SC2002-Group6#1]
In [menus/PhramacistMenu.java](https://github.com/nonnoxer/SC2002-Group6/blob/main/menus/PharmacistMenu.java#L14), PharamacistMenu should belong to Pharmacist and not the other way round.

**Comment by frost312** [comment]
By the logic you meant the pharmacist should pass itself into the PharMenu as an object in order to achieve consistency throughout the process right? Not PharMenu controls the Pharmacist class. I amended the code already! tyy
